### ISSUE TITLE
Wrong main path?

### ISSUE THREAD

**Issue by jcguarinpenaranda** [ariesjia/babel-plugin-react-bootstrap#1]
Today I started working with this module, but I get an error stating that there's no exported function. 

I noticed you have a `src/` folder in which you have the `index.js` file but you have set the package main script path to `dist/index.js` so I guess that's the problem.

**Comment by jcguarinpenaranda** [comment]
Well, now reading a little bit more, I see that you are using babel to compile the src folder to dist, because you are using some ES2015 patterns. So I guess the problem may be that the module was not built before publishing.

**Comment by ariesjia** [comment]
Sorry , I ignored the dist directory before, I  publish it  now .

**Comment by jcguarinpenaranda** [comment]
Thank you

Juan Camilo Guarín Peñaranda
Ingeniero Multimedia y Emprendedor en tecnología
Otherwise: http://owsas.com
<http://mailstat.us/tr/t/pleg6bmaikkbgvuq/h/http://owsas.com/>

2017-09-29 1:19 GMT-05:00 Chenjia <notifications@github.com>:
